import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SettingsProvider } from "@/contexts/settings-context";
import { TaskProvider } from "@/contexts/task-context";
import { TimerProvider } from "@/contexts/timer-context";
import { AnalyticsProvider } from "@/contexts/analytics-context";
import { GoogleOAuthProvider } from "@react-oauth/google";


export const metadata: Metadata = {
  title: "Foocus",
  description: "Generated by Me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-black"
      >
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SettingsProvider>
              <TaskProvider>
                <AnalyticsProvider>
                  <TimerProvider>
                    {children}
                  </TimerProvider>
                </AnalyticsProvider>
              </TaskProvider>
            </SettingsProvider>
          </ThemeProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
